name: Building Wheels

on: [workflow_dispatch]

jobs:
 
  # build wheels using action building.yml
  build_wheels:
    name: Call Composite Action
    uses: ./.github/workflows/building.yml
            
